### ISSUE TITLE
package installation fails under Ubuntu 18.04.5 - "cannot find -lh3.1"

### ISSUE THREAD

**Issue by hewag1975** [JosiahParry/placekey#14]
Hi,
I´ve successfully managed to install the h3 library und Ubuntu 18.04.5 follwing the instructions given [here](https://github.com/uber/H3). However, installation of the package using `remotes::install_github("josiahparry/placekey")` fails with the error mentioned above. 
Do you have any ideas how to resolve this?

> remotes::install_github("josiahparry/placekey")
Downloading GitHub repo josiahparry/placekey@HEAD
✓  checking for file ‘/tmp/RtmpHPS2Gi/remotes25456cb6929/JosiahParry-placekey-0773657/DESCRIPTION’ (397ms)
─  preparing ‘placekey’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘placekey_0.1.0.tar.gz’
>    
> Installing package into ‘/home/hkwage/R/x86_64-pc-linux-gnu-library/4.0’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘placekey’ ...
> ** using staged installation
> ** libs
> g++ -std=gnu++11 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.0.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
> g++ -std=gnu++11 -I"/opt/R/4.0.3/lib/R/include" -DNDEBUG  -I'/opt/R/4.0.3/lib/R/library/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c h3api.cpp -o h3api.o
> g++ -std=gnu++11 -shared -L/opt/R/4.0.3/lib/R/lib -L/usr/local/lib -o placekey.so RcppExports.o h3api.o -L/usr/local/lib -lh3.1 -L/opt/R/4.0.3/lib/R/lib -lR
> /usr/bin/ld: cannot find -lh3.1
> collect2: error: ld returned 1 exit status
> /opt/R/4.0.3/lib/R/share/make/shlib.mk:10: recipe for target 'placekey.so' failed
> make: *** [placekey.so] Error 1
> ERROR: compilation failed for package ‘placekey’
> * removing ‘/home/hkwage/R/x86_64-pc-linux-gnu-library/4.0/placekey’
> Error: Failed to install 'placekey' from GitHub:
>   (converted from warning) installation of package ‘/tmp/RtmpHPS2Gi/file254e70d8d0/placekey_0.1.0.tar.gz’ had non-zero exit status

**Comment by jannes-m** [comment]
Seems to be related to https://github.com/scottmmjackson/h3r/pull/3/. Changing `src/Makevars` from `PKG_LIBS=-L/usr/local/lib -lh3.1` to `PKG_LIBS=-L/usr/local/lib -lh3` makes disappear the error message reported by @hewag1975, however, then this error message occurs:

```sh
E> /usr/bin/ld: /usr/local/lib/libh3.a(h3Index.c.o): relocation R_X86_64_PC32 against symbol `maxH3ToChildrenSize' can not be used when making a shared object; recompile with -fPIC
E> /usr/bin/ld: final link failed: Bad value
E> collect2: error: ld returned 1 exit status
E> /opt/R/4.0.3/lib/R/share/make/shlib.mk:10: recipe for target 'placekey.so' failed
```

**Comment by jannes-m** [comment]
In accordance with this [SO post](https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error), I have added following lines to `h3/CMakeLists.txt`:

```sh
set( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -Wall --std=c++11 -O3 -fPIC" )
set( CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -Wall -O3 -fPIC" )
```

Then I re-compiled H3. And in fact this let me install **placekey**, however, when running the README example, only `NULL` was returned:

``` r
library("placekey")
get_placekey(
  street_address = "1543 Mission Street, Floor 3",
  city = "San Francisco",
  region  ="CA",
  postal_code = 94105,
  iso_country_code = "US"
)
#> NULL
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jannes-m** [comment]
Ok, my bad, one has to additionally provide an API key via the `key` argument in `get_placekey()`, then it works.

**Comment by hewag1975** [comment]
Ok, your approach works for me as well. Thanks for your support @jannes-m!!!

**Comment by JosiahParry** [comment]
Hwy all! Thank you so much for your help on this. My c and make knowledge
is zip! I’ll give this a check over the weekend then approve if all goes
well. :)))

**Comment by JosiahParry** [comment]
Merged https://github.com/JosiahParry/placekey/pull/15. Please try reinstalling!
